import = ["~/.config/alacritty/themes/themes/terminal_app.toml"]
[font]
normal = { family = "Berkeley Mono", style = "SemiCondensed" }
bold = { style = "Bold SemiCondensed" }
italic = { style = "SemiCondensed Oblique" }
bold_italic = { style = "Bold SemiCondensed Oblique" }
size = 16
[window]
decorations = "Buttonless"
[env]
TERM = "xterm-256color"
